dataset_name: thumos
train_split: [ 'validation' ]
val_split: [ 'test' ]
dataset: {
  json_file: ./data/thumos/annotations/thumos14.json,
  feat_folder: ./data/thumos/i3d_features,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 2048,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
}
model: {
  fpn_type: identity,

  #  fpn_type: fpn,

  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,

  # window size for self attention; <=1 to use full seq (ie global attention)
  #  "n_mha_win_size": -1,

  #  head_with_ln: False,
  #  fpn_with_ln: False,
  #  embd_with_ln: False,

  #  # disable abs position encoding (added to input embedding)
  #  "use_abs_pe": True,
  #  # use rel position encoding (added to self-attention)
  #  "use_rel_pe": True,

  #  # a tuple defines # layers in embed / stem / branch
  #  backbone_arch: (2, 2, 1), # 相对于没有特征金字塔

}
opt: {
  learning_rate: 0.0001,
  weight_decay: 0.05,
  epochs: 30,
  warmup_epochs: 5,
  #  epochs: 60,
  #  warmup_epochs: 10,
  type: AdamW
}
loader: {
  batch_size: 2,
  num_workers: 16,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  #  center_sample: none,
  #  center_sample_radius: 1.5,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,

  #  ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
}
output_folder: ./ckpt/
